name: Generate Pydoc Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pydoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Django
        run: pip install django

      - name: Generate Pydoc HTML
        env:
          DJANGO_SETTINGS_MODULE: my_site.settings
        run: |
          mkdir -p docs
          cd my_site
          export PYTHONPATH=$PWD
          
          # Comando corregido inmune al bug de subpaquetes
          python -c "import django; django.setup(); import pydoc; [pydoc.writedoc(m) for m in ['manage', 'blog.views', 'blog.urls']]"
          
          # Movemos los tres archivos HTML generados a la carpeta de la web
          mv *.html ../docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
