name: Generate Pydoc Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pydoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Django
        run: pip install django

      - name: Generate Pydoc HTML
        env:
          # Apunta a los settings dentro de tu estructura de doble carpeta
          DJANGO_SETTINGS_MODULE: my_site.my_site.settings
        run: |
          mkdir docs
          # Rutas exactas corregidas para que encuentre views y urls sin perderse
          python -m pydoc -w my_site/my_site/manage.py my_site/my_site/blog/views.py my_site/my_site/blog/urls.py
          mv *.html docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs